[workspace]
members = [
    "bootloader",
    "blasterball",
    "artist",
    "num",
    "lazy_static",
    "machine",
    "sync",
    "collections",
    "event_hook",
    "physics",
    "sound"
]

[profile.release]
opt-level = 0