[workspace]
members = [
    "bootloader",
    "blasterball",
    "artist",
    "num",
    "tester",
    "lazy_static",
    "machine",
    "sync",
    "drivers",
    "collections",
    "event_hook",
    "physics"
]

exclude = [
    "tester"
]