[build]
target = "../x86_64-blasterball.json"
rustflags = [
    #"-C", "link-args=-Tlinker.ld",
    "-Z", "pre-link-args=/subsystem:efi_boot_service_driver",
    "-g"
]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]